**2019.2.27 (201902270)** - Advanced and assisted charging voltage control. Refer to README.md or `acc --help` for details. - Automatically unset nonworking charging switch (fallback to cycling through all). - Daily Job Scheduler (djs) -- run `djs` or refer to its README.md to learn how to schedule commands, profiles, and even entire scripts. That's a standalone Magisk module. - Enhanced debugging tools (e.g., `acc -x|--xtrace <other option(s)>`) - Flexible framework and easy installer for app developers - Log monitoring (`acc -L`) - Major fixes and optimizations - On demand charging control files tester - Reset config with `acc -s r`. - Self-upgrade (enabled by default, virtually no impact on mobile data - acc zips weigh way less than 100 kilobytes) - Updated documentation -- added troubleshooting section and more. - Updated links and default config. - When persistent verbose is off, volatile verbose is generated (`/dev/acc/acc-daemon-*.log`). - Workaround for Magisk service.sh bug (scrip not executed)

diff --git a/common/acc b/common/acc
--- a/common/acc
+++ b/common/acc
@@ -7,11 +7,19 @@
 main() {
 
   umask 0
+  trap exxit EXIT
   set -euo pipefail
 
-  lockFile=/dev/acc/running
+  pidFile=/dev/acc/pid
   modPath=/system/etc/acc
   config=/data/media/0/acc/config.txt
+
+  # root check
+  echo
+  if ! ls /data/data 1>/dev/null 2>&1; then
+    echo "(!) Must run as root (su)"
+    exit 1
+  fi
 
   if [ ! -f $modPath/module.prop ]; then
     modPath=/sbin/.magisk/img/acc
@@ -25,21 +33,13 @@ main() {
 
   batt=$(echo /sys/class/power_supply/*attery/capacity | awk '{print $1}' | sed 's|/capacity||')
 
-  trap exxit EXIT
-
-  # root check
-  echo
-  if ! ls /data/data 1>/dev/null 2>&1; then
-    echo "(!) Must run as root (su)"
-    exit 1
-  fi
-
-  if [ ! -e $modPath ]; then
+  if [ ! -d $modPath ]; then
     echo "(!) modPath not found"
     exit 1
   fi
 
-  mkdir -p ${lockFile%/*}
+  mkdir -p ${pidFile%/*} ${config%/*}/logs
+  [ -f $config ] || install -m 0777 $modPath/default_config.txt $config
   cd /sys/class/power_supply/
 
   set +u
@@ -51,12 +51,28 @@ main() {
     -e|--enable) shift; enable_charging $@;;
     -i|--info) sed s/POWER_SUPPLY_// $batt/uevent;;
     -l|--log) shift; edit ${config%/*}/logs/acc-daemon*.log $@;;
+    -L)
+      if eval $(get_value verbose); then
+        tail -F ${config%/*}/logs/acc-daemon*.log
+      else
+        tail -F ${pidFile%/*}/acc-daemon-*.log
+      fi
+    ;;
     -r|--readme) shift; edit ${config%/*}/info/README.md $@;;
     -R|--resetstats)
       dumpsys batterystats --reset 1>/dev/null 2>&1 || :
       rm /data/system/batterystats* 2>/dev/null || :
     ;;
     -s|--set) shift; set_values $@;;
+    -t|--test)
+      shift
+      if [ -z "${1-}" ]; then
+        test_cctrl_file $(get_value switch)
+      else
+        test_cctrl_file $@
+      fi
+    ;;
+    -v|--voltage) shift; set_charging_voltage $@;;
     *) help;;
   esac
   set -u
@@ -66,17 +82,18 @@ main() {
 daemon() {
   case $1 in
     start)
-      if [ -f $lockFile ] && ps | grep -q $(sed -n 1p $lockFile); then
+      if [ -f $pidFile ] && ps | grep $(sed -n 1p $pidFile) 1>/dev/null 2>&1; then
         echo "(i) accd is already running"
       else
         echo "(i) accd started"
+        set +x
         accd
       fi
     ;;
     stop)
-      if [ -f $lockFile ] && ps | grep -q $(sed -n 1p $lockFile); then
-        kill $(cat $lockFile) 2>/dev/null || :
-        rm $lockFile
+      if [ -f $pidFile ] && ps | grep $(sed -n 1p $pidFile) 1>/dev/null 2>&1; then
+        kill $(cat $pidFile) 2>/dev/null || :
+        rm $pidFile
         enable_charging
         echo "(i) accd stopped"
       else
@@ -84,15 +101,16 @@ daemon() {
       fi
     ;;
     restart)
-      if [ -f $lockFile ] && ps | grep -q $(sed -n 1p $lockFile); then
+      if [ -f $pidFile ] && ps | grep $(sed -n 1p $pidFile) 1>/dev/null 2>&1; then
         echo "(i) accd restarted"
       else
         echo "- accd started"
       fi
+      set +x
       accd
     ;;
     *)
-      if [ -f $lockFile ] && ps | grep -q $(sed -n 1p $lockFile); then
+      if [ -f $pidFile ] && ps | grep $(sed -n 1p $pidFile) 1>/dev/null 2>&1; then
         echo "(i) accd is running"
       else
         echo "(i) accd is not running"
@@ -143,10 +161,12 @@ Usage: acc <options> <args>
 -l|--log <editor [opts]>   Open <acc-daemon-deviceName.log> w/ <editor [opts]> (default: vim|vi)
   e.g., acc -l grep ': ' (show errors only), acc -l cat >/sdcard/acc.log (yes, this also works)
 
+-L   Monitor log
+
 -r|--readme   Open <README.md> w/ <editor [opts]> (default: vim|vi)
   i.e., acc -r
 
- -R|--resetstats   Reset battery stats
+-R|--resetstats   Reset battery stats
 
 -s|--set   Show current config
   i.e., acc --set
@@ -160,15 +180,40 @@ Usage: acc <options> <args>
 -s|--set <s|switch>   Set a different charging switch from the database
   i.e., acc -s s
 
-Tips
+-s|--set <s:|switch:>   List available charging switches
 
-  Pause and resume capacities can also be set with acc <pause%> <resume%>.
-    e.g., acc 85 80
+-s|--set <s-|switch->   Unset charging switch
+
+-t|--test   Test currently set charging ctrl file
+  Return codes: 0 (works), 1 (does not work) or 2 (battery must be charging)
+
+-t|--test <file onValue offValue>   Test custom charging ctrl file
+  Return codes: 0 (works), 1 (does not work) or 2 (battery must be charging)
+
+-v|--voltage <xxxx|voltFile:xxxx>   Set charging voltage (mV) on demand (3920-4199mV)
+  e.g., acc -v 3920, acc -v /sys/class/power_supply/battery/voltage_max:4100
+
+-v|--voltage   Restore default voltage
+
+-v|--voltage :   List available charging voltage control files
+
+-v|--voltage -   Show current voltage
+
+-v|--voltage :xxxx   Evaluate and set charging voltage control files
+
+-x|--xtrace <other option(s)>   Run under set -x (debugging)
+
+Tips
 
   Commands can be chained for extended functionality.
     e.g., acc -e 30m && acc -d 6h && acc -e 85 && accd (recharge for 30 minutes, halt charging for 6 hours, recharge to 85% capacity and restart daemon)
 
-Run acc -r to see the full documentation (type ":q! <enter>" to quit).
+  Pause and resume capacities can also be set with acc <pause%> <resume%>.
+    e.g., acc 85 80
+
+  Run "djs" to learn how to schedule commands, profiles, and even entire scripts.
+
+Run acc -r to see the full documentation (type "<esc> :q! <enter>" to quit).
 HELP
 }
 
@@ -195,34 +240,42 @@ set_values() {
     7080|default) set_value capacity 5,60,70-80;;
     5960|endurance) set_value capacity 5,60,59-60;;
     4041|endurance+) set_value capacity 5,60,40-41;;
-    *) if [ -n "$1" ]; then
-         if [ -z "$2" ] && [ $1 = switch -o $1 = s ]; then
-           set_switch
-         else
-           set_value $@
-         fi
-       else
-         grep '^[a-z].*=' $config | sed 's/#.*//'
-       fi;;
+    r|reset)
+      cp -f $modPath/default_config $config
+      chmod 0777 $config
+      echo "(i) Config reset"
+      return 0
+    ;;
+    *)
+      if [ -n "$1" ]; then
+        if [ -z "$2" ] && [[ $1 = s || $1 = switch ]]; then
+          set_switch
+        elif [ "x$2" = x: ] || [[ $1 = s: || $1 = switch: ]]; then
+          list_cctrl_files
+        elif [ "x$2" = x- ] || [[ $1 = s- || $1 = switch- ]]; then
+          set_value switch
+          echo "(i) Charging switch reset"
+        else
+          set_value $@
+        fi
+      else
+        grep '^[a-z].*=' $config | sed 's/#.*//'
+      fi
+    ;;
   esac
 }
 
 
 set_switch() {
-  local s="" on="" off="" l="" i="" oIFS=$IFS
-  echo -e "(i) Available charging switches\n- Choose one and press <enter> to set it\n"
-
-  while read s; do
-    [ -f $(echo $s | awk '{print $1}') ] && l="$l
-$s"
-  done <<SWITCHES
-$(grep -Ev '#|^$' $modPath/switches.txt)
-SWITCHES
-
+  local switch="" on="" off="" oIFS=$IFS
+  echo "(i) Available charging switches"
+  echo "- Choose one and press <enter> to set it"
+  echo
   local IFS=$'\n'
-  eval 'select i in $l; do
+  eval 'select switch in $(list_cctrl_files) exit; do
+    [ x$switch = xexit ] && exit 0
     IFS=$oIFS
-    set_value switch "$i"
+    set_value switch "$switch"
     break
   done'
 }
@@ -235,9 +288,13 @@ disable_charging() {
     s=$(get_value switch | awk '{print $1}')
     off=$(get_value switch | awk '{print $3}')
     if [ -f $s ]; then
-      chmod +w $s && echo $off >$s || :
+      chmod +w $s && echo $off >$s \
+        || { echo "(!) [$switch] does not work"
+          set_value switch
+          exit 1; }
     else
-      echo -e "(!) Invalid charging switch\n"
+      echo "(!) Invalid charging switch"
+      set_value switch
       exit 1
     fi
   else
@@ -246,13 +303,15 @@ disable_charging() {
   set +u
   if [ -n "$1" ]; then
     if echo "$1" | grep -q %; then
-      echo -e "(i) Charging disabled until battery capacity <= $1\n"
+      echo "(i) Charging disabled until battery capacity <= $1"
+      echo
       until [ $(cat $batt/capacity) -le $(echo $1 | sed 's/%//') ]; do
         sleep $(get_value loopDelay)
       done
       enable_charging
     elif echo "$1" | grep -Eq 's|m|h'; then
-      echo -e "(i) Charging disabled for $1\n"
+      echo "(i) Charging disabled for $1"
+      echo
       if echo "$1" | grep -q s; then
         sleep $(echo $1 | sed 's/\s//')
       elif echo "$1" | grep -q m; then
@@ -272,19 +331,23 @@ disable_charging() {
 
 enable_charging() {
   local s="" on=""
-  daemon stop | grep -v not && echo
+  daemon stop | grep stopped || :
   if get_value switch | grep -q /; then
     s=$(get_value switch | awk '{print $1}')
     on=$(get_value switch | awk '{print $2}')
     if [ -f $s ]; then
-      chmod +w $s && echo $on >$s || :
+      chmod +w $s && echo $on >$s \
+        || { echo "(!) [$switch] does not work"
+          set_value switch
+          exit 1; }
       for l in $(get_value onPlugged); do
         t=$(echo $l | cut -d: -f1)
         v=$(echo $l | cut -d: -f2)
         [ -f $t ] && chmod +w $t && echo $v >$t || :
       done
     else
-      echo -e "(!) Invalid charging switch\n"
+      echo "(!) Invalid charging switch"
+      set_value switch
       exit 1
     fi
   else
@@ -293,13 +356,15 @@ enable_charging() {
   set +u
   if [ -n "$1" ]; then
     if echo "$1" | grep -q %; then
-      echo -e "(i) Charging enabled until battery capacity >= $1\n"
+      echo "(i) Charging enabled until battery capacity >= $1"
+      echo
       until [ $(cat $batt/capacity) -ge $(echo $1 | sed 's/%//') ]; do
         sleep $(get_value loopDelay)
       done
       disable_charging
     elif echo "$1" | grep -Eq 's|m|h'; then
-      echo -e "(i) Charging enabled for $1\n"
+      echo "(i) Charging enabled for $1"
+      echo
       if echo "$1" | grep -q s; then
         sleep $(echo $1 | sed 's/\s//')
       elif echo "$1" | grep -q m; then
@@ -336,13 +401,13 @@ set_cap() {
 
 switch_loop() {
   local s="" on="" off="" default=""
-  while read s; do
+  while IFS= read -r s; do
     if [ -f $(echo $s | awk '{print $1}') ]; then
       on=$(echo $s | awk '{print $2}')
       off=$(echo $s | awk '{print $3}')
       s=$(echo $s | awk '{print $1}')
       default=$(sed -n 1p $s)
-      chmod +w $s && eval "echo \$$1" >$s && sleep 1 || :
+      chmod +w $s && eval "echo \$$1" >$s && sleep 1 || continue
       if { [ $1 = off ] && ! grep -Eiq 'dis|not' $batt/status; } \
         || { [ $1 = on ] && grep -Eiq 'dis|not' $batt/status; }
       then
@@ -355,6 +420,152 @@ switch_loop() {
 $(grep -Ev '#|^$' $modPath/switches.txt)
 SWITCHES
 }
+
+
+set_charging_voltage() {
+
+  local value=""
+  local setVoltage=false
+  local dVolt=${pidFile%/*}/dVolt
+  local file=$(echo -n $(get_value voltFile))
+
+  if echo ${1-} | grep -q '^[34]' && [ $1 -ge 3920 ] && [ $1 -le 4199 ] ; then # mV
+    setVoltage=true
+    value=$1
+  elif echo ${1-} | grep -q ':[34]' && [ ${1##*:} -ge 3920 ] && [ ${1##*:} -le 4199 ]; then # override voltFile
+    setVoltage=true
+    value=${1##*:}
+    [[ $1 = */* ]] && file=$(echo ${1%:*}) || vfiles_prompt $value
+  elif echo ${1-} | grep -q '^\-$'; then # show current voltage
+    if [ -f ${pidFile%/*}/dVolt ]; then
+      file=$(awk '{print $1}' ${pidFile%/*}/dVolt)
+      cat $file
+    else
+      echo default
+    fi
+    return 0
+  elif [ -z "${1-}" ]; then # restore default voltage
+    if [ -f ${pidFile%/*}/dVolt ]; then
+      file=$(awk '{print $1}' ${pidFile%/*}/dVolt)
+      value=$(awk '{print $2}' ${pidFile%/*}/dVolt)
+      chmod +w $file && echo $value > $file \
+      && echo "(i) Default voltage ($(sed -n 1p $file)) was successfully restored."
+    else
+      echo "(i) Default voltage is already set."
+    fi
+    return 0
+  elif [ x${1-} = x: ]; then
+    list_vfiles
+    return 0
+  else
+    echo "(!) Invalid input"
+    echo "- Recall that the accepted voltage range is 3920-4199mV."
+    return 1
+  fi
+
+  if $setVoltage; then
+    if [ -f $file ]; then
+      if chmod +w $file && sed "s/^..../$value/" $file > $file 2>/dev/null && grep -q "^$value" $file; then
+        [ -f $dVolt ] || echo "$file $(sed -n 1p $file)" > $dVolt
+        echo "(i) Charging voltage set to $(sed -n 1p $file)."
+      else
+        echo "(!) Either $(echo -n $file) is not the right file or your kernel does not support this feature."
+        return 1
+      fi
+    else
+      echo "(!) No such file, $file"
+      return 1
+    fi
+  fi
+}
+
+
+list_vfiles(){
+  grep -E '/constant_charge_voltage$|/voltage_max$' ${config%/*}/logs/acc-power_supply-*.log | sed 's/$/\n/'
+}
+
+
+vfiles_prompt() {
+  local file="" success=false
+  local PS3="(?) Choice, <enter>: "
+  eval 'select file in $(list_vfiles) exit; do
+    echo
+    [ x$file = xexit ] && exit
+    set_charging_voltage $file:$1 && success=true || :
+    if $success; then
+      echo
+      acc -s voltFile $file 1>/dev/null
+      echo "(i) voltFile=$file --> config.txt"
+      exit 0
+    else
+      echo
+      vfiles_prompt $1
+    fi
+  done'
+}
+
+
+list_cctrl_files() {
+  local file=""
+  while IFS= read -r file; do
+    [ ! -f $(echo $file | awk '{print $1}') ] || echo $file
+  done <<SWITCHES
+$(grep -Ev '#|^$' $modPath/switches.txt)
+SWITCHES
+}
+
+
+test_cctrl_file() {
+
+  local daemonUp=true
+  local on=$(echo "$@" | awk '{print $2}')
+  local off=$(echo "$@" | awk '{print $3}')
+  local switch=$(echo "$@" | awk '{print $1}')
+  [ -z "$switch" ] || local defaultValue=$(sed -n 1p $switch)
+
+  daemon stop | grep stopped 1>/dev/null 2>&1 || daemonUp=false
+
+  if grep -Eiq 'dis|not' $batt/status; then
+    echo "(!) Battery must be charging"
+    ! $daemonUp || daemon start 1>/dev/null
+    return 2
+  fi
+
+  if [ -n "${1:-}" ]; then
+    chmod +w $switch && echo $off > $switch || :
+    sleep 1
+    if grep -Eiq 'dis|not' $batt/status; then
+      echo "(i) [$switch] works"
+      echo $on > $switch
+      ! $daemonUp || daemon start 1>/dev/null
+      return 0
+    else
+      echo "(!) [$switch] does not work"
+      echo $defaultValue > $switch
+      ! $daemonUp || daemon start 1>/dev/null
+      return 1
+    fi
+  else
+    disable_charging 1>/dev/null
+    if grep -Eiq 'dis|not' $batt/status; then
+      echo "(i) Supported device"
+      enable_charging 1>/dev/null
+      ! $daemonUp || daemon start 1>/dev/null
+      return 0
+    else
+      echo "(!) Unsupported device"
+      ! $daemonUp || daemon start 1>/dev/null
+      return 1
+    fi
+  fi
+}
+
+
+# debugging
+if [[ "${1:-x}" = "-x" || "${1:-x}" = "--xtrace" ]]; then
+  shift
+  set -x
+fi
 
 
 main $@
