# v2017.10.15 (201710150) - Additional devices support. - Built-in zip binary to pack debugging data. - Users can now specify the charging control file for cs to work with. Check the README for additional info.

diff --git a/system/xbin/cs b/system/xbin/cs
--- a/system/xbin/cs
+++ b/system/xbin/cs
@@ -7,7 +7,7 @@
 # Environment
 h=/data/.cs_settings
 st=/data/.cs_sON
-export PATH=/dev/magisk/bin:$PATH
+export PATH=/dev/magisk/bin:/magisk/cs/bin:$PATH
 echo
 
 
@@ -53,6 +53,7 @@ ctrl_file() {
 	elif ! model 'Galaxy Note' && model Samsung; then switch /batt_slate_mode 0 1
 		[ -f "$s" ] || switch s=/sys/devices/platform/battery/power_supply/battery/batt_slate_mode
 	elif model Huawei; then switch s=/sys/class/hw_power/charger/charge_data/enable_charger
+		[ -f "$s" ] || switch s=/sys/devices/platform/huawei_charger/enable_charger
 	elif model 'Amazon Fire'; then switch "/device/Charging_Enable"
 	elif model 'Nexus 4'; then switch s=/sys/module/pm8921_charger/parameters/disabled 0 1
 	elif model 'Nexus 10'; then switch "s=/sys/devices/virtual/power_supply/manta-battery/charge_enabled"
@@ -67,11 +68,21 @@ ctrl_file() {
 	elif model 'Xiaomi Redmi Note 2'; then switch s=/sys/devices/platform/battery/ChargerEnable
 	fi
 	
-	# Working with standard/generic control file
+	# Devices confimed working with standard/generic control file
 	# OnePlus 3, Moto Z Play, Sony Xperia Z5 Premium
 	
 	[ -f "$s" ] || switch charging_enabled # It appears this one is the most common among devices running near-stock Android.
 	[ -f "$s" ] || switch battery_charging_enabled
+	
+	# User setup
+	if [ -f /sdcard/cs_ctrl.txt ]; then
+		. /sdcard/cs_ctrl.txt
+		if [ ! -f "s" ]; then
+			echo "(!) cs: The specified control file doesn't exist"
+			echo
+			exit 1
+		fi
+	fi
 	
 	if [ ! -f "$s" ]; then echo "(!) cs: Unsupported device"
 		echo
@@ -261,7 +272,7 @@ elif [ -z "$1" ]; then
 		echo
 		c_info
 		echo
-		echo "(i) Press CTRL+C to abort"
+		echo "(i) Press CTRL (Vol. Down) + C to abort"
 		[ "$POWER_SUPPLY_CAPACITY" -ge "75" ] && sleep 20 || sleep 60
 	done
 	c_loop
@@ -283,7 +294,7 @@ until [ "$POWER_SUPPLY_CAPACITY" -ge "$1" ]; do
 	echo
 	c_info
 	echo
-	echo "(i) Press CTRL+C to abort"
+	echo "(i) Press CTRL (Vol. Down) + C to abort"
 	[ "$POWER_SUPPLY_CAPACITY" -ge "75" ] && sleep 20 || sleep 60
 done
 
