2018.12.10

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,268 +1,144 @@
-#!/sbin/sh -x
-# Magic Charging Switch (mcs) Installer
-# (c) 2017-2018, VR25 @ xda-developers
-# License: GPL v3+
+#!/sbin/sh
+##########################################################################################
+#
+# Magisk Module Template Install Script
+# by topjohnwu
+#
+##########################################################################################
 
-# detect whether in bootmode
-getprop | grep zygote | grep -q running && bootMode=true || bootMode=false
+TMPDIR=/dev/tmp
+INSTALLER=$TMPDIR/install
+# Always mount under tmp
+MOUNTPATH=$TMPDIR/magisk_img
 
-# default perms
+# Default permissions
 umask 022
 
-ui_print() {
-  $bootMode && echo -e "$1" || echo -e "ui_print $1\nui_print" >> /proc/self/fd/$OUTFD
+# Initial cleanup
+rm -rf $TMPDIR 2>/dev/null
+mkdir -p $INSTALLER
+
+# echo before loading util_functions
+ui_print() { echo "$1"; }
+
+require_new_magisk() { ###
+unzip -o "$ZIP" config.sh module.prop -d $INSTALLER >&2
+. $INSTALLER/config.sh
+install_system
 }
 
-grep_prop() {
-  REGEX="s/^$1=//p"
-  shift
-  FILES=$@
-  [ -z "$FILES" ] && FILES='/system/build.prop'
-  sed -n "$REGEX" $FILES 2>/dev/null | head -n 1
-}
-
-is_mounted() { mountpoint -q "$1" 2>/dev/null; }
-
-mount_image() {
-	ui_print "- Mounting $1 to $2"
-	[ -d "$2" ] || mkdir -p "$2"
-	if (! is_mounted $2); then
-		loopDevice=
-		for LOOP in 0 1 2 3 4 5 6 7; do
-			if (! is_mounted $2); then
-				loopDevice=/dev/block/loop$LOOP
-				[ -f "$loopDevice" ] || mknod $loopDevice b 7 $LOOP 2>/dev/null
-				losetup $loopDevice $1
-				if [ "$?" -eq "0" ]; then
-					mount -t ext4 -o loop $loopDevice $2
-					is_mounted $2 || /system/bin/toolbox mount -t ext4 -o loop $loopDevice $2
-					is_mounted $2 || /system/bin/toybox mount -t ext4 -o loop $loopDevice $2
-				fi
-				is_mounted $2 && break
-			fi
-		done
-	fi
-	if ! is_mounted $2; then
-    ui_print " "
-    ui_print "(!) Failed to mount $IMG"
-    ui_print " "
-    exit 1
-  fi
-}
-
-set_perm() {
-  chown $2:$3 "$1" || exit 1
-  chmod $4 "$1" || exit 1
-  [ -z "$5" ] && chcon 'u:object_r:system_file:s0' "$1" || chcon $5 "$1"
-}
-
-set_perm_recursive() {
-  find "$1" -type d 2>/dev/null | while read dir; do
-	set_perm "$dir" $2 $3 $4 $6
-  done
-  find "$1" -type f -o -type l 2>/dev/null | while read file; do
-	set_perm "$file" $2 $3 $5 $6
-  done
-}
-
-request_size_check() {
-  reqSizeM=`du -s $1 | cut -f1`
-  reqSizeM=$((reqSizeM / 1024 + 1))
-}
-
-request_zip_size_check() {
-  reqSizeM=`unzip -l "$1" | tail -n 1 | awk '{ print int($1 / 1048567 + 1) }'`
-}
-
-image_size_check() {
-  e2fsck -yf $1 >&2
-  curBlocks=`e2fsck -n $1 2>/dev/null | grep $1 | cut -d, -f3 | cut -d\  -f2`;
-  curUsedM=`echo "$curBlocks" | cut -d/ -f1`
-  curSizeM=`echo "$curBlocks" | cut -d/ -f1`
-  curFreeM=$(((curSizeM - curUsedM) * 4 / 1024))
-  curUsedM=$((curUsedM * 4 / 1024 + 1))
-  curSizeM=$((curSizeM * 4 / 1024))
-}
-
-mod_info() {
-  grep_prop "$1" $INSTALLER/module.prop
-}
-
-print_modname() {
-  ui_print " "
-  ui_print "$(mod_info name) ($(mod_info id)) $(mod_info version)"
-  ui_print "$(mod_info author)"
-  ui_print "Powered by Magisk (@topjohnwu)"
-  ui_print " "
-}
-
-set_permissions() {
-  # Only some special files require specific permissions
-  # The default permissions should be good enough for most cases
-
-  # Here are some examples for the set_perm functions:
-
-  # set_perm_recursive  <dirname>                <owner> <group> <dirpermission> <filepermission> <contexts> (default: u:object_r:system_file:s0)
-  # set_perm_recursive  $modPath/system/lib       0       0       0755            0644
-
-  # set_perm  <filename>                         <owner> <group> <permission> <contexts> (default: u:object_r:system_file:s0)
-  # set_perm  $modPath/system/bin/app_process32   0       2000    0755         u:object_r:zygote_exec:s0
-  # set_perm  $modPath/system/bin/dex2oat         0       2000    0755         u:object_r:dex2oat_exec:s0
-  # set_perm  $modPath/system/lib/libart.so       0       0       0644
-
-  # The following are default permissions, DO NOT remove
-  set_perm_recursive  $tmpModPath  0  0  0755  0644
-
-  for f in $tmpModPath/bin/* $(find $tmpModPath -type f -name $modID) $(find $tmpModPath -type f -name *.sh); do
-    [ -f "$f" ] && set_perm $f 0 0 0755
-  done
-}
+##########################################################################################
+# Environment
+##########################################################################################
 
 OUTFD=$2
-ZIP="$3"
+ZIP="$3" ###
 
-readlink /proc/$$/fd/$OUTFD 2>/dev/null | grep /tmp >/dev/null
-if [ "$?" -eq "0" ]; then
-  OUTFD=0
+mount /data 2>/dev/null
 
-  for FD in `ls /proc/$$/fd`; do
-	readlink /proc/$$/fd/$FD 2>/dev/null | grep pipe >/dev/null
-	if [ "$?" -eq "0" ]; then
-	  ps | grep " 3 $FD " | grep -v grep >/dev/null
-	  if [ "$?" -eq "0" ]; then
-		OUTFD=$FD
-		break
-	  fi
-	fi
-  done
+# Load utility functions
+if [ -f /data/adb/magisk/util_functions.sh ]; then
+  . /data/adb/magisk/util_functions.sh
+elif [ -f /data/magisk/util_functions.sh ]; then
+  NVBASE=/data
+  . /data/magisk/util_functions.sh
+else
+  require_new_magisk
 fi
 
-tmpDir=/dev/tmp
-INSTALLER=$tmpDir/install
-mountPath=$tmpDir/magisk_img
-$bootMode && imgName=magisk_merge.img || imgName=magisk.img
-[ -d /data/adb/magisk ] && IMG=/data/adb/$imgName || IMG=/data/$imgName
+# Use alternative image if in BOOTMODE
+$BOOTMODE && IMG=$NVBASE/magisk_merge.img
 
-if [ ! -d /data/adb/magisk ] && [ ! -d /data/magisk ]; then
-	ui_print " "
-	ui_print "(!) No Magisk installation found or installed version is not supported"
-	ui_print " "
-	exit 1
-fi
+# Preperation for flashable zips
+setup_flashable
 
-# initial cleanup
-rm -rf $tmpDir 2>/dev/null
-mkdir -p $INSTALLER 2>/dev/null
+# Mount partitions
+mount_partitions
 
-unzip -o "$ZIP" 'common/*' module.prop -d $INSTALLER >&2
+# Detect version and architecture
+api_level_arch_detect
 
-modID="`grep_prop id $INSTALLER/module.prop`"
-tmpModPath=$mountPath/$modID
-modPath=$tmpModPath
+# You can get the Android API version from $API, the CPU architecture from $ARCH
+# Useful if you are creating Android version / platform dependent mods
 
-# find modPath
-if $bootMode; then
-  for mountPoint in /sbin/.core/img /magisk; do
-    if [ -d "$mountPoint/.core" ] || [ -d "$mountPoint/lost+found" ]; then
-      mountPoint=$mountPoint
-      modPath=$mountPoint/$modID
-      break
-    fi
-  done
-  is_mounted $mountPoint && mkdir -p $modPath 2>/dev/null \
-    || { echo -e "\n(!) $IMG mount point not found\n"; exit 1; }
-fi
+# Setup busybox and binaries
+$BOOTMODE && boot_actions || recovery_actions
+
+##########################################################################################
+# Preparation
+##########################################################################################
+
+# Extract common files
+unzip -o "$ZIP" module.prop config.sh 'common/*' -d $INSTALLER >&2
+
+[ ! -f $INSTALLER/config.sh ] && abort "! Unable to extract zip file!"
+# Load configurations
+. $INSTALLER/config.sh
+
+# Check the installed magisk version
+MIN_VER=`grep_prop minMagisk $INSTALLER/module.prop`
+[ ! -z $MAGISK_VER_CODE -a $MAGISK_VER_CODE -ge $MIN_VER ] || require_new_magisk
+MODID=`grep_prop id $INSTALLER/module.prop`
+MODPATH=$MOUNTPATH/$MODID
 
 # Print mod name
 print_modname
 
-$bootMode || ui_print "- Mounting partitions"
-mount -o ro /system 2>/dev/null
-mount -o ro /vendor 2>/dev/null
-mount /data 2>/dev/null
-mount /cache 2>/dev/null
+# Please leave this message in your flashable zip for credits :)
+ui_print "******************************"
+ui_print "Powered by Magisk (@topjohnwu)"
+ui_print "******************************"
 
+##########################################################################################
+# Install
+##########################################################################################
+
+# Get the variable reqSizeM. Use your own method to determine reqSizeM if needed
 request_zip_size_check "$ZIP"
 
-if [ -f "$IMG" ]; then
-  ui_print "- $IMG detected!"
-  image_size_check $IMG
-  if [ "$reqSizeM" -gt "$curFreeM" ]; then
-	SIZE=$(((reqSizeM + curUsedM) / 32 * 32 + 64))
-	ui_print "- Resizing $IMG to ${SIZE}M..."
-	resize2fs $IMG ${SIZE}M >&2
-  fi
-else
-  SIZE=$((reqSizeM / 32 * 32 + 64));
-  ui_print "- Creating $IMG with size ${SIZE}M"
-  make_ext4fs -l ${SIZE}M $IMG >&2
+# This function will mount $IMG to $MOUNTPATH, and resize the image based on $reqSizeM
+mount_magisk_img
+
+install_module ###
+
+# Handle replace folders
+for TARGET in $REPLACE; do
+  mktouch $MODPATH$TARGET/.replace
+done
+
+# Auto Mount
+$AUTOMOUNT && touch $MODPATH/auto_mount
+
+# prop files
+$PROPFILE && cp -af $INSTALLER/common/system.prop $MODPATH/system.prop
+
+# Module info
+cp -af $INSTALLER/module.prop $MODPATH/module.prop
+if $BOOTMODE; then
+  # Update info for Magisk Manager
+  mktouch /sbin/.core/img/$MODID/update
+  cp -af $INSTALLER/module.prop /sbin/.core/img/$MODID/module.prop
 fi
 
-mount_image $IMG $mountPath
+# post-fs-data mode scripts
+$POSTFSDATA && cp -af $INSTALLER/common/post-fs-data.sh $MODPATH/post-fs-data.sh
 
-##########################################################################################
-# module-specific code
-##########################################################################################
-
-# environment
-modData=/data/media/$modID
-modInfo=$modData/info
-
-# cleanup obsolete data
-[ "$(grep_prop versionCode $modPath/module.prop)" -lt "201808060" ] \
-  && rm -rf $modData 2>/dev/null
-[ "$(grep_prop versionCode $modPath/module.prop)" -lt "201807300" ] \
-  && rm $modInfo/Change* 2>/dev/null
-
-# create module paths
-rm -rf $tmpModPath 2>/dev/null
-mkdir -p $tmpModPath
-mkdir -p $modInfo 2>/dev/null
-
-# extract module files
-ui_print "- Extracting module files"
-unzip -o "$ZIP" -d $INSTALLER >&2
-cd $INSTALLER
-mv common/* $tmpModPath/
-[[ ! -d /system/xbin && ! -d /system_root/system/xbin ]] \
-  && mv $tmpModPath/system/xbin $tmpModPath/system/bin
-mv -f License.md README.md $modInfo/
-
-# auto-mount
-touch $tmpModPath/auto_mount
-
-##########################################################################################
-
-# module info
-cp $INSTALLER/module.prop $tmpModPath/
-
-# update info for Magisk Manager
-if $bootMode; then
-  touch $modPath/update
-  cp $INSTALLER/module.prop $modPath/
-fi
+# service mode scripts
+$LATESTARTSERVICE && cp -af $INSTALLER/common/service.sh $MODPATH/service.sh
 
 ui_print "- Setting permissions"
 set_permissions
 
-$bootMode || ui_print "- Unmounting partitions"
-umount $mountPath
-losetup -d $loopDevice
-rmdir $mountPath
+##########################################################################################
+# Finalizing
+##########################################################################################
 
-# shrink the image if possible
-image_size_check $IMG
-NEWDATASIZE=$((curUsedM / 32 * 32 + 32))
-if [ "$curSizeM" -gt "$NEWDATASIZE" ]; then
-  ui_print "- Shrinking $IMG to ${NEWDATASIZE}M..."
-  resize2fs $IMG ${NEWDATASIZE}M >&2
-fi
+# Unmount magisk image and shrink if possible
+unmount_magisk_img
 
-if ! $bootMode; then
-  umount /system
-  umount /vendor 2>/dev/null
-fi
+$BOOTMODE || recovery_cleanup
+rm -rf $TMPDIR
 
-ui_print "- End"
-ui_print " "
+ui_print "- Done"
+version_info ###
 exit 0
