**2020.2.23-dev (202002230)** - Updated strings > Note: incompatible with AccA versions lower than 1.0.21
**2020.2.22-r1-dev (202002221)**
- acc -D: show accd version and PID as well
- acc -F: optimizations
- acc -s s: fixed "print_known_cs: not found"
- acc -v: new output format - `version (version_code)`
> Note: incompatible with AccA versions lower than 1.0.21

**2020.2.22-dev (202002220)**
- Ability to set/nullify multiple properties with a single command (e.g., `acc -s prop1=value "prop2=value1 value2 ..." prop3=`)
- `acc --uninstall` (-U) and the flashable uninstaller remove AccA as well
- Better localization support
- capacity_sync and cooldown cycle improvements
- Changes made by `apply_on_boot()` and `apply_on_plug()` are reverted automatically when appropriate
- config.txt contains a comprehensive help text as well
- Dedicated current control commmands
- Custom configuration for specific devices (`acc/oem-custom.sh`)
- Enhanced commmand list and examples (`acc -h`)
- Extended device support (ASUS, MediaTek, Pixel 4/XL, Razer, 1+7 and more)
- General wizard (`acc` command)
- Greater charging control flexibility
- More modular design
- New config format and more flexible APIs
- Optimized busybox setup
- Prevent power events from waking the screen during the cooldown cycle
- `runCmdOnPause`
- Self-disable after a bootloop event
- Symlink `installDir` to `/data/adb/acc` and `/data/adb/modules/acc`
- The help text (acc -h), documentation (acc -r), logs (acc -l) and config (acc -c) open in vim/vi by default (scrollable)
- Universal zip flasher (`acc -F "zip_file"`)
- Updated documentation and framework
> Notes: incompatible with AccA versions lower than 1.0.21; config will be reset

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -1,7 +1,10 @@
 #!/system/bin/sh
 # $id Installer/Upgrader
-# Copyright (c) 2019, VR25 (xda-developers.com)
+# Copyright (c) 2019-2020, VR25 (xda-developers)
 # License: GPLv3+
+
+# override the official Magisk module installer
+SKIPUNZIP=1
 
 set +x
 echo
@@ -16,23 +19,25 @@ set -x
 trap 'e=$?; echo; exit $e' EXIT
 
 # set up busybox
+#BB#
 if [ -d /sbin/.magisk/busybox ]; then
-  [[ $PATH == /sbin/.magisk/busybox* ]] || PATH=/sbin/.magisk/busybox:$PATH
-elif [ -d /sbin/.core/busybox ]; then
-  [[ $PATH == /sbin/.core/busybox* ]] || PATH=/sbin/.core/busybox:$PATH
+  [[ $PATH == /sbin/.magisk/busybox:* ]] || PATH=/sbin/.magisk/busybox:$PATH
 else
-  [[ $PATH == /dev/.busybox* ]] || PATH=/dev/.busybox:$PATH
-  if ! mkdir -m 700 /dev/.busybox 2>/dev/null; then
-    if [ -x /data/adb/magisk/busybox ]; then
-      /data/adb/magisk/busybox --install -s /dev/.busybox
-    elif which busybox > /dev/null; then
+  mkdir -p -m 700 /dev/.busybox
+  [[ $PATH == /dev/.busybox:* ]] || PATH=/dev/.busybox:$PATH
+  if [ ! -x /dev/.busybox/busybox ]; then
+    if which busybox > /dev/null; then
       busybox --install -s /dev/.busybox
+    elif [ -f /data/adb/busybox ]; then
+      chmod 700 /data/adb/busybox
+      /data/adb/busybox --install -s /dev/.busybox
     else
       echo "(!) Install busybox binary first"
       exit 3
     fi
   fi
 fi
+#/BB#
 
 # root check
 if [ $(id -u) -ne 0 ]; then
@@ -43,8 +48,8 @@ fi
 print() { sed -n "s|^$1=||p" ${2:-$srcDir/module.prop}; }
 
 set_perms() {
-  local owner=${2:-0} perms=0600 target=$(readlink -f $1)
-  if echo $target | grep -q '.*\.sh$' || [ -d $target ]; then perms=0700; fi
+  local owner=${2:-0} perms=600 target=$(readlink -f $1)
+  if echo $target | grep -q '.*\.sh$' || [ -d $target ]; then perms=700; fi
   chmod $perms $target
   chown $owner:$owner $target
   restorecon $target > /dev/null 2>&1 || :
@@ -55,110 +60,127 @@ set_perms_recursive() {
   find $1 2>/dev/null | while read target; do set_perms $target $owner; done
 }
 
-set -euo pipefail
+set -euo pipefail 2>/dev/null || :
 
 # set source code directory
 [ -f $PWD/${0##*/} ] && srcDir=$PWD || srcDir=${0%/*}
+srcDir=${srcDir/#"${0##*/}"/"."}
 
 # unzip flashable zip if source code is unavailable
 if [ ! -f $srcDir/module.prop ]; then
   srcDir=/dev/.tmp
   rm -rf $srcDir 2>/dev/null || :
   mkdir $srcDir
-  unzip -o ${ZIP:-${3:-}} -d $srcDir/ >&2
+  unzip ${ZIP:-${3-}} -d $srcDir/ >&2
 fi
 
 name=$(print name)
 author=$(print author)
 version=$(print version)
 versionCode=$(print versionCode)
-installDir=${installDir0:-/data/data/mattecarra.accapp/files}
-config=/data/media/0/$id/${id}.conf
-
-# migrate/restore config
-[ -f $config ] || mv ${config%/*}/config.txt $config 2>/dev/null || :
-if [ -d ${config%/*} ] && [ ! -d /data/adb/${id}-data ]; then
-  mv $config ${config%/*}/config.txt 2>/dev/null || :
-  (cd /data/media/0; mv ${config%/*} ${id}-data
-  tar -cf - ${id}-data | tar -xf - -C /data/adb)
-  rm -rf ${id}-data
-fi
+installDir=${installDir0:=/data/data/mattecarra.accapp/files}
 config=/data/adb/${id}-data/config.txt
+
+# restore config backup
 [ -f $config ] || cp /data/media/0/.${id}-config-backup.txt $config 2>/dev/null || :
 
-configVer=$(print versionCode $config 2>/dev/null || :)
+configVer=$(print configVerCode $config 2>/dev/null || :)
 
 # check/set parent installation directory
 [ -d $installDir ] || installDir=/sbin/.magisk/modules
-[ -d $installDir ] || installDir=/sbin/.core/img
 [ -d $installDir ] || installDir=/data/adb
 [ -d $installDir ] || { echo "(!) /data/adb/ not found\n"; exit 1; }
 
 
+# install
+
 cat << EOF
 $name $version
-Copyright (c) 2017-2019, $author
+Copyright (c) 2017-2020, $author
 License: GPLv3+
 
 (i) Installing in $installDir/$id/...
 EOF
 
+/sbin/.acc-en --daemon stop > /dev/null 2>&1 || :
 
-(pkill -9 -f "/$id (-|--)|/${id}d.sh" ) || :
+rm -rf $(readlink -f /sbin/.$id/$id || :) $installDir/$id \
+  /data/adb/$id /sbin/.magisk/modules/$id 2>/dev/null || :
 
-# install
-rm -rf $(readlink -f /sbin/.$id/$id) $installDir/$id 2>/dev/null || :
 cp -R $srcDir/$id/ $installDir/
-installDir=$installDir/$id
-[ ${installDir0:-x} == x ] && installDir0=/data/data/mattecarra.accapp/files/$id || installDir0=$installDir0/$id
+installDir=$(readlink -f $installDir/$id)
+installDir0=$installDir0/$id
+[ ! -d $installDir0 ] || installDir0=$(readlink -f $installDir0)
 cp $srcDir/module.prop $installDir/
 
 mkdir -p ${config%/*}/info
 cp -f $srcDir/*.md ${config%/*}/info
+[ $installDir == /data/adb/$id ] || ln -s $installDir /data/adb/
 
-case $installDir in
-  /data/adb/$id|$installDir0)
-    mv $installDir/service.sh $installDir/${id}-init.sh;;
-  *)
-    ln $installDir/service.sh $installDir/post-fs-data.sh;;
-esac
 
-# patch/upgrade config
-if [ -f $config ]; then
-  if [ ${configVer:-0} -lt 201910130 ] \
-      || [ ${configVer:-0} -gt $(print versionCode $installDir/default-config.txt) ]
-  then
-    rm $config
-#  else
-#    if [ $configVer -lt 201906290 ]; then
-#      echo prioritizeBattIdleMode=false >> $config
-#      sed -i '/^versionCode=/s/=.*/=201906290/' $config
-#    fi
-#    if [ $configVer -lt 201907080 ]; then
-#      sed -i '/^loopDelay=/s/=.*/=10,30/' $config
-#      sed -i '/^versionCode=/s/=.*/=201907080/' $config
-#    fi
-#    if [ $configVer -lt 201907090 ]; then
-#      sed -i '/^rebootOnUnplug=/d' $config
-#      sed -i '/^versionCode=/s/=.*/=201907090/' $config
-#    fi
-#    if [ $configVer -lt 201909260 ]; then
-#      sed -i '/^loopDelay=/s/,30/,15/' $config
-#      sed -i '/^versionCode=/s/=.*/=201909260/' $config
-#    fi
-  fi
+if [ $installDir != /sbin/.magisk/modules/$id ]; then
+  mv $installDir/service.sh $installDir/${id}-init.sh
+
+  # enable upgrading through Magisk Manager
+  ln -s $installDir /sbin/.magisk/modules/$id 2>/dev/null || :
+
+  # set up alternate initializer (Magisk service.d)
+  cat << EOF > /data/adb/service.d/${id}-init.sh
+#!/system/bin/sh
+# alternate $id initializer
+(until [ -d /storage/emulated/0/?ndroid ]; do sleep 10; done
+if [ -f $installDir/${id}-init.sh ]; then
+  $installDir/${id}-init.sh
+else
+  rm \$0
+fi
+exit 0 &) &
+exit 0
+EOF
+  chmod 700 /data/adb/service.d/${id}-init.sh
+
+  # set up cleanup script
+  cat << EOF > /data/adb/service.d/${id}-cleanup.sh
+#!/system/bin/sh
+# $id post-uninstall cleanup
+(until [ -d /storage/emulated/0/?ndroid ]; do sleep 15; done
+if [ ! -f $installDir/module.prop ]; then
+  rm /data/adb/$id /data/adb/${id}-data /data/adb/modules/$id \$0 2>/dev/null
+fi
+exit 0 &) &
+exit 0
+EOF
+  chmod 700 /data/adb/service.d/${id}-cleanup.sh
 fi
 
+
+touch /sbin/.magisk/modules/$id/skip_mount 2>/dev/null || :
+
+# patch/reset config
+if [ -f $config ]; then
+  dConfVer=$(print configVerCode $installDir/default-config.txt)
+  if [[ ${configVer:-0} -gt $dConfVer || ${configVer:-0} -lt 202002220 ]]; then
+    rm $config /sdcard/acc-logs-*.tar.bz2 2>/dev/null || :
+  # else
+    # if [ $configVer -lt 201906290 ]; then
+      # echo prioritizeBattIdleMode=false >> $config
+      # sed -i '/^configVerCode=/s/=.*/=201906290/' $config
+    # fi
+  fi
+  unset dConfVer
+fi
+
+# flashable uninstaller
 cp -f $srcDir/bin/${id}-uninstaller.zip /data/media/0/
 
 # set perms
 set_perms_recursive ${config%/*}
-chmod 0666 /data/media/0/${id}-uninstaller.zip
+chmod 666 /data/media/0/${id}-uninstaller.zip
 case $installDir in
   /data/*/files/$id)
     pkg=${installDir%/files/$id}
     pkg=${pkg##/data*/}
-    owner=$(grep $pkg /data/system/packages.list | awk '{print $2}')
+    owner=$(grep $pkg /data/system/packages.list | cut -d ' ' -f 2)
     set_perms_recursive ${installDir%/*} $owner
   ;;
   *)
@@ -166,7 +188,7 @@ case $installDir in
   ;;
 esac
 
-set +euo pipefail
+set +euo pipefail 2>/dev/null || :
 
 
 cat << EOF
@@ -178,25 +200,26 @@ EOF
 
 
 # print changelog
-tail -n +$(grep -n \($versionCode\) ${config%/*}/info/README.md | cut -d: -f1) \
-  ${config%/*}/info/README.md | sed 's/^/    /'
+sed -n "\|\($versionCode\)|,\$s|^|    |p" ${config%/*}/info/README.md
 
 
 cat << EOF
 
   LINKS
-    - ACC app: github.com/MatteCarra/AccA/
+    - ACC app: GitHub.com/MatteCarra/AccA/
     - Battery University: batteryuniversity.com/learn/article/how_to_prolong_lithium_based_batteries/
-    - Donate: paypal.me/vr25xda/
-    - Daily Job Scheduler: github.com/VR-25/djs/
-    - Facebook page: facebook.com/VR25-at-xda-developers-258150974794782/
-    - Git repository: github.com/VR-25/$id/
+    - Daily Job Scheduler: GitHub.com/VR-25/djs/
+    - Facebook page: fb.me/vr25xda/
+    - Git repository: GitHub.com/VR-25/$id/
+    - Liberapay: liberapay.com/VR25/
+    - Patreon: patreon.com/vr25/
+    - PayPal: paypal.me/vr25xda/
     - Telegram channel: t.me/vr25_xda/
     - Telegram group: t.me/${id}_group/
     - Telegram profile: t.me/vr25xda/
     - XDA thread: forum.xda-developers.com/apps/magisk/module-magic-charging-switch-cs-v2017-9-t3668427/
 
-(i) Important info: https://bit.ly/2TRqRz0
+(i) Power supply logs (help needed): https://bit.ly/2TRqRz0
 
 (i) Rebooting is unnecessary.
 - $id can be used right now.
@@ -208,6 +231,9 @@ EOF
 
 echo
 trap - EXIT
+
+# remove bootloop lock file
+rm /data/adb/${id}-data/logs/.bootlooped 2>/dev/null
 
 # initialize $id
 if grep -q /storage/emulated /proc/mounts; then
